title: EtiNL blogpost
description: A blog about my Data Science or personnal projects
author: Etienne Lanzeray
avatar: /Avatar.png
email: etienne.lanzeray@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: Avatar.png
social:
  name: Etienne Lanzeray
  links:
    - https://github.com/EtiNL
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
